### ISSUE TITLE
HTML version Freeze when taking damage

### ISSUE THREAD

**Issue by rydergreyson** [Tankzors/Builds#4] opened 2023-03-06 22:45 UTC
Hey
Thanks for bringing my fav game back to life!
When you get shot  on the HTML version the entire game freezes and you have to reload the page.
Doesn't matter what browser I try it in.

**Comment by RblSb** [comment] 2023-03-06 23:37
I can reproduce this on Safari. This can be fixed with `window.navigator.vibrate = function() {}` execution in browser console, or adding such script to https://github.com/Tankzors/Builds/blob/master/docs/html5/index.html (better with User-Agent check).
I dont want to revive sources to make new game build currently, but maybe you can solve this yourself?

**Comment by rydergreyson** [comment] 2023-03-06 23:51
> I can reproduce this on Safari. This can be fixed with `window.navigator.vibrate = function() {}` execution in browser console, or adding such script to https://github.com/Tankzors/Builds/blob/master/docs/html5/index.html (better with User-Agent check).
> I dont want to revive sources to make new game build currently, but maybe you can solve this yourself?

unfortunately I don't know the first thing about web scripting

**Closed as completed** 2023-03-07 10:05 UTC

**Comment by RblSb** [comment] 2023-03-07 10:13
Should work now. I would still recommend playing in Chrome-based/Firefox browsers, since music is also broken in Safari for some reason.

**Comment by rydergreyson** [comment] 2023-03-07 11:17
> Should work now. I would still recommend playing in Chrome-based/Firefox browsers, since music is also broken in Safari for some reason.

Do you take donations? If not can I buy you a cup of coffee or something via paypal? Playing Tankzors has made my day and I want to show my appreciation for your efforts!

**Comment by RblSb** [comment] 2023-03-07 11:56
Not for Russia anymore. If you have steam, you maybe can buy [steam gift card](https://store.steampowered.com/digitalgiftcards/selectgiftcard) and [send it to me](https://steamcommunity.com/id/RblSb/) (i will add you to friends before) or maybe send gift code to `msrblsb <nobotspam> @ <nobotspam> gmail.com`

**Comment by rydergreyson** [comment] 2023-03-09 10:23
> Not for Russia anymore. If you have steam, you maybe can buy [steam gift card](https://store.steampowered.com/digitalgiftcards/selectgiftcard) and [send it to me](https://steamcommunity.com/id/RblSb/) (i will add you to friends before) or maybe send gift code to `msrblsb@gmail.com`

Ok. Give me some time. I'll email you when possible :D
